// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrspf0aYFIJJDOan6wrcPjsUNUyQ2fV8',
    appId: '1:235878615356:web:58d6c91d3e336caeac7639',
    messagingSenderId: '235878615356',
    projectId: 'door-to-programming',
    authDomain: 'door-to-programming.firebaseapp.com',
    storageBucket: 'door-to-programming.firebasestorage.app',
    measurementId: 'G-353KKM92JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLpRgmLWxo5yyDKy2bBFiisE3f5N2ZpI',
    appId: '1:235878615356:android:7e527d639d226c10ac7639',
    messagingSenderId: '235878615356',
    projectId: 'door-to-programming',
    storageBucket: 'door-to-programming.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2BeHDyECKWuzT9ypLw_5mUrgnRwIxVc',
    appId: '1:235878615356:ios:c9ff91b968936623ac7639',
    messagingSenderId: '235878615356',
    projectId: 'door-to-programming',
    storageBucket: 'door-to-programming.firebasestorage.app',
    iosBundleId: 'com.example.doorToProgramming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2BeHDyECKWuzT9ypLw_5mUrgnRwIxVc',
    appId: '1:235878615356:ios:c9ff91b968936623ac7639',
    messagingSenderId: '235878615356',
    projectId: 'door-to-programming',
    storageBucket: 'door-to-programming.firebasestorage.app',
    iosBundleId: 'com.example.doorToProgramming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASrspf0aYFIJJDOan6wrcPjsUNUyQ2fV8',
    appId: '1:235878615356:web:ee1e026cb6ef89cfac7639',
    messagingSenderId: '235878615356',
    projectId: 'door-to-programming',
    authDomain: 'door-to-programming.firebaseapp.com',
    storageBucket: 'door-to-programming.firebasestorage.app',
    measurementId: 'G-S7SCWNWGDX',
  );
}
